name: Build modelsaddles
on:
  push:
jobs:
  build-modelsaddle:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
          - tag: gemma3-4b
            models: gemma3:4b
          - tag: granite3.2-vision-2b
            models: granite3.2-vision:2b
          - tag: moondream-1.8b
            models: moondream:1.8b
    steps:
      - name: Skip build if image exists
        run: |
          if skopeo inspect docker://quay.io/ncao/modelsaddle-catalog:${{ matrix.image.tag }}; then
            echo "CONTINUE=false" >> "$GITHUB_ENV"
          else
            echo "CONTINUE=true" >> "$GITHUB_ENV"
          fi
      - name: Login to Quay.io
        if: ${{ fromJSON(env.CONTINUE) }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set up Docker Buildx
        if: ${{ fromJSON(env.CONTINUE) }}
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        if: ${{ fromJSON(env.CONTINUE) }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Containerfile
          tags: quay.io/ncao/modelsaddle-catalog:${{ matrix.image.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: MODELS=${{ matrix.image.models }}
